// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD64rkBWSGUMMBUBeREx9V-ddqO5bCQ4Po',
    appId: '1:944145791602:web:a02b3a72fc254f004ba0eb',
    messagingSenderId: '944145791602',
    projectId: 'projectaa1-2e971',
    authDomain: 'projectaa1-2e971.firebaseapp.com',
    storageBucket: 'projectaa1-2e971.appspot.com',
    measurementId: 'G-NP3FSCNSTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5S_S-vGN1DHUALnVG1e2jknVgZPh9shY',
    appId: '1:944145791602:android:34bf897494ca8dbc4ba0eb',
    messagingSenderId: '944145791602',
    projectId: 'projectaa1-2e971',
    storageBucket: 'projectaa1-2e971.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcEGAQQN8MACXQSRpfdJFOWPBpgqWmGGo',
    appId: '1:944145791602:ios:2165f89f52f4686c4ba0eb',
    messagingSenderId: '944145791602',
    projectId: 'projectaa1-2e971',
    storageBucket: 'projectaa1-2e971.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcEGAQQN8MACXQSRpfdJFOWPBpgqWmGGo',
    appId: '1:944145791602:ios:2165f89f52f4686c4ba0eb',
    messagingSenderId: '944145791602',
    projectId: 'projectaa1-2e971',
    storageBucket: 'projectaa1-2e971.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD64rkBWSGUMMBUBeREx9V-ddqO5bCQ4Po',
    appId: '1:944145791602:web:a5c27c0e07ad1bc84ba0eb',
    messagingSenderId: '944145791602',
    projectId: 'projectaa1-2e971',
    authDomain: 'projectaa1-2e971.firebaseapp.com',
    storageBucket: 'projectaa1-2e971.appspot.com',
    measurementId: 'G-5GSV2LZSVP',
  );
}
